### ISSUE TITLE
Removing a User presents errors

### ISSUE THREAD

**Issue by jswindell** [hrkymkw/Blip#9]
I was presented with two separate errors while attempting to remove an existing User:
1. Unexpected number of unique usernames:
   ![image](https://cloud.githubusercontent.com/assets/722549/8298313/5da0186e-1935-11e5-9672-50ffd37d4b5c.png)
2. Referenced User may exist within other parts of the system (e.g., Messages table)
   ![image](https://cloud.githubusercontent.com/assets/722549/8298328/8cd51c10-1935-11e5-9540-595e760c69e8.png)

**Comment by hrkymkw** [comment]
Added an unique index on User.UserName.
If duplicate user names already exist, they need to be manually removed in the DB before running "Update-database" for the new change to take effect in the local DB.

**Comment by jswindell** [comment]
It's good you added the unique index, but what about the other issue #2?

**Comment by hrkymkw** [comment]
Fixed the second issue.
If the user to be deleted is linked to any existing message, the user's active status will be set to false instead of being deleted entirely in the database.
I will update the Account Index view to show tabbed forms, one showing active users and the other showing inactive/deleted users.
